# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###
# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token b4ac6d032cb4bd117a059dbe08f1f036df3fe584

{
  "title": "Шкаф 5",
  "description": "dfghjk"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/11/
Content-Type: application/json
Authorization: Token b4ac6d032cb4bd117a059dbe08f1f036df3fe584

{
  "status": "OPEN"
}

###

# попытка поменять объявление без аунтификации
PATCH {{baseUrl}}/advertisements/14/
Content-Type: application/json

{
  "status": "CLOSED"
}

###

# попытка поменять объявление КРИВОЙ токен
PATCH {{baseUrl}}/advertisements/14/
Content-Type: application/json
Authorization: Token 4ac6d032cb4bd117a059dbe08f1f036df3fe584

{
  "status": "CLOSED"
}
###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-10-01
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json


###

# попытка удалить объявление
DELETE {{baseUrl}}/advertisements/14/
Content-Type: application/json
Authorization: Token b4ac6d032cb4bd117a059dbe08f1f036df3fe584

###

# попытка удалить объявление без авторизации
DELETE {{baseUrl}}/advertisements/14/
Content-Type: application/json


###

# попытка удалить объявление кривой токен
DELETE {{baseUrl}}/advertisements/12/
Content-Type: application/json
Authorization: Token 4ac6d032cb4bd117a059dbe08f1f036df3fe584


